export const financialEndpoints = {
  dashboard: () => '/financial/dashboard',
  cashRegisterCurrent: () => '/cash-register/current',
  cashRegisterHistory: () => '/cash-register/history',
  cashRegisterOpen: () => '/cash-register/open',
  cashRegisterMovements: () => '/cash-register/movements',
  cashRegisterClose: () => '/cash-register/close',
  receivables: () => '/receivables',
  receivableSettle: (id: string) => `/receivables/${id}/settle`,
  payables: () => '/payables',
  payablePay: (id: string) => `/payables/${id}/pay`,
  cashFlow: () => '/financial/cash-flow',
  entries: () => '/financial/entries',
  categories: () => '/financial/categories',
};
